# Generated by Django 4.1.4 on 2022-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_image_product_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='path',
            new_name='image',
        ),
    ]
